"
set autoindent
set background=dark
set backspace=indent,eol,start
set cursorline
set encoding=utf8
set expandtab
set hlsearch
set list
set listchars=trail:·,tab:▷·
set nobomb
set nocompatible
set nofoldenable
set ruler
set secure
set shiftwidth=4
set smartcase
set ignorecase
set t_Co=256
set wildmenu
set shiftround
set tabstop=4
set lazyredraw
set laststatus=2
"
syntax on

" color schema
set background=dark
colo molokai
" plugin
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'majutsushi/tagbar'
Plug 'sheerun/vim-polyglot'
call plug#end()

map <C-n> :NERDTreeToggle<CR>
nmap <F8> :TagbarToggle<CR>
"
"https://vim.fandom.com/wiki/Toggle_auto-indenting_for_code_paste
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode
